//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace micro.autom.MqttBroker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("micro.autom.MqttBroker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_off {
            get {
                object obj = ResourceManager.GetObject("cloud_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_on {
            get {
                object obj = ResourceManager.GetObject("cloud_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be read. Reason:.
        /// </summary>
        internal static string FormBrokeLog_buttonRefreshLog_Click_Error {
            get {
                return ResourceManager.GetString("FormBrokeLog_buttonRefreshLog_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainForm_Form1_FormClosing_Button {
            get {
                return ResourceManager.GetString("MainForm_Form1_FormClosing_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit and stop the Broker?.
        /// </summary>
        internal static string MainForm_FormClosing_Message {
            get {
                return ResourceManager.GetString("MainForm_FormClosing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose The Location of the service Folder. Usually located in [Application Directory]/service.
        /// </summary>
        internal static string MainForm_setBrokerFolderToolStripMenuItem_Click_Message {
            get {
                return ResourceManager.GetString("MainForm_setBrokerFolderToolStripMenuItem_Click_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process is closed.
        /// </summary>
        internal static string Message_BrokerInfo_Process_is_closed {
            get {
                return ResourceManager.GetString("Message_BrokerInfo_Process_is_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose The Location of the service Folder. Usually located in [Application Directory]/service.
        /// </summary>
        internal static string MqttCustomBroker_Start_folder_Dialog_Message {
            get {
                return ResourceManager.GetString("MqttCustomBroker_Start_folder_Dialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap programm_picture_mikroPNS {
            get {
                object obj = ResourceManager.GetObject("programm_picture_mikroPNS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The broker will stop to change the credentials..
        /// </summary>
        internal static string resource_change_pass_dialog_info {
            get {
                return ResourceManager.GetString("resource_change_pass_dialog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty or contain &apos;:&apos;.
        /// </summary>
        internal static string resource_error_field {
            get {
                return ResourceManager.GetString("resource_error_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed. Something went wrong please contact the system administrator..
        /// </summary>
        internal static string resource_failed_contact_admin {
            get {
                return ResourceManager.GetString("resource_failed_contact_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting Down Broker.
        /// </summary>
        internal static string resource_header_passdialog_warning {
            get {
                return ResourceManager.GetString("resource_header_passdialog_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Row.
        /// </summary>
        internal static string UserDatabase_buttonDelete_Click_Select_Row {
            get {
                return ResourceManager.GetString("UserDatabase_buttonDelete_Click_Select_Row", resourceCulture);
            }
        }
    }
}
